import type { ScanResult, Finding, GasHint, Severity } from "../types";

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: "🔴",
  high:     "🟠",
  medium:   "🟡",
  low:      "🟢",
  info:     "🔵",
  gas:      "⛽",
};

const SEVERITY_ORDER: Severity[] = ["critical", "high", "medium", "low", "info", "gas"];

function sortFindings(findings: Finding[]): Finding[] {
  return [...findings].sort(
    (a, b) =>
      SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity)
  );
}

// ─── Markdown Report ──────────────────────────────────────────────────────────

export function generateMarkdownReport(result: ScanResult): string {
  const lines: string[] = [];
  const { summary } = result;

  lines.push("# ChainProof Security Audit Report");
  lines.push("");
  lines.push(`**Generated:** ${result.timestamp}`);
  lines.push(`**ChainProof version:** ${result.version}`);
  lines.push(`**Files scanned:** ${result.files.length}`);
  lines.push("");

  // Executive Summary
  lines.push("## Executive Summary");
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("|----------|-------|");
  lines.push(`| ${SEVERITY_EMOJI.critical} Critical | ${summary.critical} |`);
  lines.push(`| ${SEVERITY_EMOJI.high} High     | ${summary.high} |`);
  lines.push(`| ${SEVERITY_EMOJI.medium} Medium   | ${summary.medium} |`);
  lines.push(`| ${SEVERITY_EMOJI.low} Low      | ${summary.low} |`);
  lines.push(`| ${SEVERITY_EMOJI.info} Info     | ${summary.info} |`);
  lines.push(`| ${SEVERITY_EMOJI.gas} Gas      | ${summary.gas} |`);
  lines.push(`| **Total** | **${summary.total}** |`);
  lines.push("");

  if (summary.critical > 0 || summary.high > 0) {
    lines.push(
      "> ⚠️ **This contract has critical or high severity findings. " +
      "Do not deploy to mainnet without addressing these issues.**"
    );
    lines.push("");
  }

  // Findings per file
  for (const file of result.files) {
    if (file.parseError) {
      lines.push(`## ${file.file}`);
      lines.push("");
      lines.push(`> ❌ Parse error: ${file.parseError}`);
      lines.push("");
      continue;
    }

    const allFindings = sortFindings(file.findings);
    if (allFindings.length === 0 && file.gasHints.length === 0) continue;

    lines.push(`## ${file.file}`);
    lines.push("");
    if (file.slitherRan) {
      lines.push("_Scanned with ChainProof AST engine + Slither_");
    } else {
      lines.push("_Scanned with ChainProof AST engine (Slither not available)_");
    }
    lines.push("");

    // Vulnerability findings
    if (allFindings.length > 0) {
      lines.push("### Vulnerability Findings");
      lines.push("");

      allFindings.forEach((f, idx) => {
        lines.push(
          `#### ${idx + 1}. ${SEVERITY_EMOJI[f.severity]} [${f.severity.toUpperCase()}] ${f.title}`
        );
        lines.push("");
        lines.push(`- **ID:** \`${f.id}\`${f.swcId ? ` ([${f.swcId}](https://swcregistry.io/docs/${f.swcId}))` : ""}`);
        lines.push(`- **Location:** Line ${f.line}`);
        if (f.llmEnhanced) lines.push("- **Enhanced by:** AI analysis ✨");
        lines.push("");
        lines.push("**Description**");
        lines.push("");
        lines.push(f.description);
        lines.push("");
        lines.push("**Recommendation**");
        lines.push("");
        lines.push(f.recommendation);
        lines.push("");

        if (f.snippet) {
          lines.push("**Affected Code**");
          lines.push("");
          lines.push("```solidity");
          lines.push(f.snippet);
          lines.push("```");
          lines.push("");
        }

        lines.push("---");
        lines.push("");
      });
    }

    // Gas hints
    if (file.gasHints.length > 0) {
      lines.push("### Gas Optimization Hints");
      lines.push("");
      file.gasHints.forEach((h: GasHint, idx: number) => {
        lines.push(`#### ${idx + 1}. ⛽ Line ${h.line} — ${h.description.split(".")[0]}`);
        lines.push("");
        lines.push(h.description);
        lines.push("");
        lines.push(`**Estimated saving:** ${h.estimatedSaving}`);
        lines.push("");
        if (h.snippet) {
          lines.push("```solidity");
          lines.push(h.snippet);
          lines.push("```");
          lines.push("");
        }
      });
    }
  }

  lines.push("---");
  lines.push("");
  lines.push(
    "_This report was generated by [ChainProof](https://github.com/your-org/chainproof). " +
    "It is not a substitute for a manual security audit by a qualified professional._"
  );

  return lines.join("\n");
}

// ─── JSON Report ──────────────────────────────────────────────────────────────

export function generateJSONReport(result: ScanResult): string {
  return JSON.stringify(result, null, 2);
}

// ─── Table (terminal) ─────────────────────────────────────────────────────────

export function generateTableReport(result: ScanResult): string {
  const lines: string[] = [];
  const { summary } = result;

  lines.push("\n╔═══════════════════════════════════════════════════════════╗");
  lines.push("║              CHAINPROOF AUDIT REPORT                     ║");
  lines.push("╚═══════════════════════════════════════════════════════════╝\n");

  lines.push(`  Files scanned : ${result.files.length}`);
  lines.push(`  Timestamp     : ${result.timestamp}\n`);

  lines.push("  FINDINGS SUMMARY");
  lines.push("  ─────────────────────────────────────────");
  lines.push(`  ${SEVERITY_EMOJI.critical} Critical : ${summary.critical}`);
  lines.push(`  ${SEVERITY_EMOJI.high} High     : ${summary.high}`);
  lines.push(`  ${SEVERITY_EMOJI.medium} Medium   : ${summary.medium}`);
  lines.push(`  ${SEVERITY_EMOJI.low} Low      : ${summary.low}`);
  lines.push(`  ${SEVERITY_EMOJI.info} Info     : ${summary.info}`);
  lines.push(`  ${SEVERITY_EMOJI.gas} Gas      : ${summary.gas}`);
  lines.push(`  ─────────────────────────────────────────`);
  lines.push(`  Total    : ${summary.total}\n`);

  for (const file of result.files) {
    if (file.findings.length === 0 && file.gasHints.length === 0) continue;
    lines.push(`  FILE: ${file.file}`);
    sortFindings(file.findings).forEach((f) => {
      lines.push(
        `    ${SEVERITY_EMOJI[f.severity]} [${f.severity.padEnd(8)}] Line ${String(f.line).padEnd(4)} ${f.title}`
      );
    });
    file.gasHints.forEach((h) => {
      lines.push(`    ⛽ [gas     ] Line ${String(h.line).padEnd(4)} ${h.description.split(".")[0]}`);
    });
    lines.push("");
  }

  return lines.join("\n");
}
