import * as core from "@actions/core";
import * as github from "@actions/github";
import * as fs from "fs";
import * as path from "path";
import {
  scan,
  generateMarkdownReport,
  generateJSONReport,
  isSlitherAvailable,
} from "@chainproof/core";
import type { ScanConfig, ScanResult, ContractMetrics } from "@chainproof/core";

// ─── Build PR comment ─────────────────────────────────────────────────────────

function buildPRComment(result: ScanResult): string {
  const { summary } = result;
  const emoji =
    summary.critical > 0
      ? "🚨"
      : summary.high > 0
      ? "⚠️"
      : summary.total > 0
      ? "💡"
      : "✅";

  const lines: string[] = [];
  lines.push(`## ${emoji} ChainProof Audit Report`);
  lines.push("");

  if (summary.total === 0) {
    lines.push("No vulnerability findings detected. ✅");
    return lines.join("\n");
  }

  lines.push("| Severity | Count |");
  lines.push("|----------|-------|");
  if (summary.critical) lines.push(`| 🔴 Critical | ${summary.critical} |`);
  if (summary.high)     lines.push(`| 🟠 High     | ${summary.high} |`);
  if (summary.medium)   lines.push(`| 🟡 Medium   | ${summary.medium} |`);
  if (summary.low)      lines.push(`| 🟢 Low      | ${summary.low} |`);
  if (summary.info)     lines.push(`| 🔵 Info     | ${summary.info} |`);
  if (summary.gas)      lines.push(`| ⛽ Gas      | ${summary.gas} |`);
  lines.push("");

  if (summary.critical > 0 || summary.high > 0) {
    lines.push(
      "> 🛑 **Critical or high severity issues found. This PR should not be merged until resolved.**"
    );
    lines.push("");
  }

  // ── Top 3 highest-risk contracts (from metrics) ────────────────────────
  if (result.metrics && result.metrics.length > 0) {
    const top3 = result.metrics
      .slice()
      .sort((a, b) => b.riskScore - a.riskScore)
      .slice(0, 3);

    lines.push("### 🔥 Top 3 Highest-Risk Contracts");
    lines.push("");
    lines.push("| Rank | Contract | File | Risk Score | LOC | Avg CC | Inheritance Depth |");
    lines.push("|------|----------|------|------------|-----|--------|-------------------|");

    top3.forEach((m, i) => {
      const badge = i === 0 ? "🥇" : i === 1 ? "🥈" : "🥉";
      lines.push(
        `| ${badge} ${i + 1} | ${m.contract} | ${m.file} | ${m.riskScore}/100 | ${m.linesOfCode} | ${m.avgCyclomaticComplexity} | ${m.inheritanceDepth} |`
      );
    });
    lines.push("");

    const highCC = result.metrics.flatMap((m) =>
      m.highComplexityFunctions.map((f) => ({ ...f, contract: m.contract }))
    );
    if (highCC.length > 0) {
      lines.push("### ⚠️ High-Complexity Functions (CC > 10)");
      lines.push("");
      for (const f of highCC) {
        lines.push(`- **${f.contract}::${f.name}** — CC: ${f.cc} — _Consider refactoring_`);
      }
      lines.push("");
    }
  }

  // Show top 5 findings inline
  const topFindings = result.files
    .flatMap((f) => f.findings)
    .filter((f) => f.severity === "critical" || f.severity === "high")
    .slice(0, 5);

  if (topFindings.length > 0) {
    lines.push("### Top Findings");
    lines.push("");
    topFindings.forEach((f) => {
      const sev = f.severity === "critical" ? "🔴" : "🟠";
      lines.push(`**${sev} ${f.title}** — \`${f.file}:${f.line}\``);
      lines.push(`> ${f.description.split(".")[0]}.`);
      lines.push("");
    });
  }

  lines.push("---");
  lines.push(
    "_Generated by [ChainProof](https://github.com/your-org/chainproof). " +
    "Download the full audit report from the Actions artifacts._"
  );

  return lines.join("\n");
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function run() {
  try {
    const targets = core
      .getInput("targets")
      .split(" ")
      .filter(Boolean);

    const minSeverity = core.getInput("min-severity") as ScanConfig["minSeverity"];
    const useSlither = core.getInput("use-slither") === "true";
    const useMetrics = core.getInput("use-metrics") !== "false";
    const apiKey = core.getInput("api-key") || process.env.ANTHROPIC_API_KEY;
    const uploadReport = core.getInput("upload-report") === "true";
    const failOnGas = core.getInput("fail-on-gas") === "true";

    core.info(`[ChainProof] Scanning: ${targets.join(", ")}`);
    core.info(`[ChainProof] Min severity: ${minSeverity}`);
    core.info(`[ChainProof] Slither: ${useSlither && isSlitherAvailable() ? "enabled" : "disabled"}`);
    core.info(`[ChainProof] LLM: ${apiKey ? "enabled" : "disabled"}`);
    core.info(`[ChainProof] Metrics: ${useMetrics ? "enabled" : "disabled"}`);

    const config: ScanConfig = {
      targets,
      useSlither: useSlither && isSlitherAvailable(),
      useLLM: !!apiKey,
      useMetrics,
      apiKey,
      minSeverity,
    };

    const result = await scan(config);
    const { summary } = result;

    // ── Set outputs ────────────────────────────────────────────────────────────
    core.setOutput("critical-count", String(summary.critical));
    core.setOutput("high-count", String(summary.high));
    core.setOutput("total-count", String(summary.total));

    // ── Write reports ──────────────────────────────────────────────────────────
    const mdReport = generateMarkdownReport(result);
    const jsonReport = generateJSONReport(result);
    const reportDir = path.join(process.cwd(), "chainproof-reports");
    fs.mkdirSync(reportDir, { recursive: true });

    const mdPath = path.join(reportDir, "audit-report.md");
    const jsonPath = path.join(reportDir, "audit-report.json");
    fs.writeFileSync(mdPath, mdReport, "utf-8");
    fs.writeFileSync(jsonPath, jsonReport, "utf-8");
    core.setOutput("report-path", mdPath);

    // ── Post PR comment ────────────────────────────────────────────────────────
    const token = process.env.GITHUB_TOKEN;
    const ctx = github.context;

    if (token && ctx.payload.pull_request) {
      const octokit = github.getOctokit(token);
      const prNumber = ctx.payload.pull_request.number;

      // Find and update existing ChainProof comment, or create new one
      const { data: comments } = await octokit.rest.issues.listComments({
        ...ctx.repo,
        issue_number: prNumber,
      });

      const existing = comments.find(
        (c) =>
          c.user?.login === "github-actions[bot]" &&
          c.body?.includes("ChainProof Audit Report")
      );

      const commentBody = buildPRComment(result);

      if (existing) {
        await octokit.rest.issues.updateComment({
          ...ctx.repo,
          comment_id: existing.id,
          body: commentBody,
        });
      } else {
        await octokit.rest.issues.createComment({
          ...ctx.repo,
          issue_number: prNumber,
          body: commentBody,
        });
      }

      core.info("[ChainProof] PR comment posted");
    }

    // ── Annotate files with findings ──────────────────────────────────────────
    for (const fileResult of result.files) {
      for (const finding of fileResult.findings) {
        const annotate =
          finding.severity === "critical" || finding.severity === "high"
            ? core.error
            : finding.severity === "medium"
            ? core.warning
            : core.notice;

        annotate(`[${finding.id}] ${finding.title}: ${finding.description}`, {
          file: finding.file,
          startLine: finding.line,
          endLine: finding.lineEnd ?? finding.line,
          title: finding.title,
        });
      }
    }

    // ── Fail CI on threshold ───────────────────────────────────────────────────
    const RANK: Record<string, number> = {
      critical: 5, high: 4, medium: 3, low: 2, info: 1,
    };
    const minRank = RANK[minSeverity ?? "high"] ?? 4;
    const blockingFindings = result.files
      .flatMap((f) => f.findings)
      .filter((f) => (RANK[f.severity] ?? 0) >= minRank);

    if (blockingFindings.length > 0) {
      core.setFailed(
        `[ChainProof] ${blockingFindings.length} ${minSeverity}+ severity findings detected. ` +
        "Resolve before merging."
      );    }

    if (failOnGas && summary.gas > 0) {
      core.setFailed(`[ChainProof] ${summary.gas} gas optimization hints found.`);
      return;
    }

    core.info(
      `[ChainProof] ✅ No ${minSeverity}+ severity issues found. ${summary.total} total hints.`
    );
  } catch (err) {
    core.setFailed(`[ChainProof] Action failed: ${err}`);
  }
}

run();
